[formatter]
array-table-style-alignment = false
null-type-hint = "pipe"
space-after-cast-unary-prefix-operators = false

[linter.rules]
ambiguous-function-call = { enabled = true, level = "error" }
assertion-style = { level = "error" }
block-statement = { level = "error" }
identity-comparison = { level = "error" }
no-redundant-string-concat = { level = "error" }
