[formatter]
array-table-style-alignment = false
inline-empty-classlike-braces = false
inline-empty-closure-braces = false
inline-empty-constructor-braces = false
inline-empty-function-braces = false
inline-empty-method-braces = false
null-type-hint = "pipe"
space-after-cast-unary-prefix-operators = false

[linter.rules]
ambiguous-constant-access = { enabled = true, level = "error" }
ambiguous-function-call = { enabled = true, level = "error" }
array-style = { enabled = true, level = "error" }
assertion-style = { level = "error" }
block-statement = { level = "error" }
class-name = { enabled = true, level = "error" }
constant-name = { enabled = true, level = "error" }
disallowed-functions = { enabled = true, level = "error", functions = ["compact", "extract", "settype"] }
enum-name = { enabled = true, level = "error" }
explicit-nullable-param = { enabled = true, level = "error" }
interface-name = { enabled = true, level = "error" }
lowercase-keyword = { enabled = true, level = "error" }
lowercase-type-hint = { enabled = true, level = "error" }
method-name = { enabled = true, level = "error", camel = true, either = false }
no-alias-function = { enabled = true, level = "error" }
no-assign-in-condition = { enabled = true, level = "error" }
no-else-clause = { enabled = true, level = "error" }
no-empty-comment = { enabled = true, level = "error" }
no-fully-qualified-global-function = { enabled = true, level = "error" }
no-fully-qualified-global-constant = { enabled = true, level = "error" }
no-is-null = { enabled = true, level = "error" }
no-redundant-final = { enabled = true, level = "error" }
no-redundant-parentheses = { enabled = true, level = "error" }
no-redundant-string-concat = { level = "error" }
no-redundant-use = { enabled = true, level = "error" }
no-unused-closure-capture = { enabled = true, level = "error" }
property-name = { enabled = true, level = "error", camel = true, either = false }
single-class-per-file = { enabled = true, level = "error" }
strict-types = { enabled = true, level = "error" }
trait-name = { enabled = true, level = "error" }
valid-docblock = { enabled = true, level = "error" }
variable-name = { enabled = true, level = "error", camel = true, either = false }
yoda-conditions = { enabled = true, level = "error", mode = "deny" }
