name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3", "8.4"]
        composer_flags:
          - '--prefer-lowest'
          - ''

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Prepare environment
        run: |
          echo "COMPOSER_CACHE=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction ${{ matrix.composer_flags }} > /dev/null

      - name: Tests
        run: |
          vendor/bin/phpunit
