name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]
        composer_flags:
          - '--prefer-lowest'
          - ''

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-${{ matrix.php }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          echo "COMPOSER_CACHE=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction ${{ matrix.composer_flags }} > /dev/null

      - name: Tests
        run: |
          vendor/bin/phpunit
