name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ['7.4', '8.0']

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-${{ matrix.php }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer Cache
        uses: actions/cache@v1
        with:
          path: $(composer config cache-files-dir)
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --no-interaction > /dev/null

      - name: Tests
        run: |
          vendor/bin/phpunit
